--[[
 Noindex: true
]]
local info = debug.getinfo(1,'S');
script_path = info.source:match[[^@?(.*[\/])[^\/]-$]]


-- Script generated by Lokasenna's GUI Builder
function Msg(param)
    reaper.ShowConsoleMsg(tostring(param).."\n")
end
log = io.open(script_path .. "bin\\GrimSync.log", "r")
if log then
	-- text = GUI.Val("TextEditor1")
	-- GUI.Val("TextEditor1", text.."\n"..log:read("*all"))
	Msg(log:read("*all"))
	Msg("Sync Completed!")
    log:close()
else
	Msg("ERROR:Log not found!")
end